### ISSUE TITLE
Aria2Android gets closed when swiping in recents

### ISSUE THREAD

**Issue by ClockGen** [devgianlu/Aria2Android#11]
Even with permanent notification, app is getting closed when you swipe it away in recents menu on android 8.1 (LineageOS 15.1).

**Comment by devgianlu** [comment]
I've been looking around for a solution for quite a while now, but nothing seem to solve this issue. The closest thing to an always running service is restarting it immediately after the app closes; this anyway isn't a solution for us.

All and all I think this strictly depends on which device/ROM you are using, my phone does this for everything. Other may not. Looking forward to a solution.

**Comment by devgianlu** [comment]
Asus Zenfone 2 (ZE551ML) will leave the service going even when the app is swiped out.

This is strictly phone dependent.
