### ISSUE TITLE
Feature request: prepackaged aria2 binary

### ISSUE THREAD

**Issue by ClockGen** [devgianlu/Aria2Android#12]
Hello, I love Aria2Android, together with Aria2App they make the most powerful download manager on android, however, some people may not be happy (mainly f-droid users) with the need of downloading aria2 binary from remote servers. It seems to be a good idea to embed a fallback aria2 binary into the apk (while still allowing to download and use different aria2 versions later). This, however, would require building aria2 itself in this project, since f-droid won't allow to include prebuilt binaries.

**Comment by devgianlu** [comment]
The binaries are pulled directly from the aria2 repository and are build by the author. Anyway, you can always import your own binary from the "Download bin" screen with the button in the top right corner.

I don't think F-Droid would allow such a CPU-intensive build on their servers.
