### ISSUE TITLE
Compatibility with Android Tv

### ISSUE THREAD

**Issue by Gotrek77** [devgianlu/Aria2Android#13]
Hi,
Thanks for your work. I have tried to install aria2android on Nvidia Shield Tv that have Android TV, but the app doesn't appear on Google play store.
I tried to install it through apk sent to the box through ES File Explorer, but after installed I can't download the binary distribution of aria2.

Please can you add support for Android TV ?

Thanks in advance

**Comment by devgianlu** [comment]
You'll need to compile the aria2 binary for whatever architecture your TV is using. Unluckily the GitHub repository provides only the executable for ARM devices.

**Comment by Gotrek77** [comment]
Nvidia shield is arm64 based.

**Comment by devgianlu** [comment]
You still need to compile a different binary. I can't help with this.
