### ISSUE TITLE
I cannot use 'P3TERX/aria2.conf' in the software.

### ISSUE THREAD

**Issue by Magic989** [devgianlu/Aria2Android#138]
Hello, I cannot use the "P3TERX/aria2.conf" configuration file in the software, no matter where I place the file. The logs indicate that the software cannot read "delete.sh" and "clean.sh." My system is Android 13.

**Comment by Magic989** [comment]
[Project address](https://github.com/P3TERX/aria2.conf)

**Comment by devgianlu** [comment]
I am sorry but this usage is not supprted, you have to create. In Android, aria2c won't have the permissions to execute those files.
