### ISSUE TITLE
SSL/TLS handshake failure

### ISSUE THREAD

**Issue by cacophobe** [devgianlu/Aria2Android#18]
Getting a SSL/TLS handshake failure Error on anything I try to download:

1546608153898|2.0.2|INFO
  -> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: self signed certificate in certificate chain

**Comment by M86xKC** [comment]
I have the same problem

**Comment by devgianlu** [comment]
Try adding `--check-certificate` and setting it to `false`. That was present in the older version and I forgot to add it again.

**Comment by M86xKC** [comment]
@devgianlu this **fixed**  it, gj

**Comment by cacophobe** [comment]
That does fix it, but probably should be set as default. Thank you for looking into it.

**Comment by devgianlu** [comment]
This fix will be in the next release.
