### ISSUE TITLE
SD CARD NO PERMISSION

### ISSUE THREAD

**Issue by ShaoXinSen** [devgianlu/Aria2Android#19]
![screenshot_20190108-200752_aria2android](https://user-images.githubusercontent.com/13616801/50829990-46bcd480-1381-11e9-9377-e58973ae2804.jpg)

**Comment by devgianlu** [comment]
Which Android version? This might be an OS restriction.

**Comment by ShaoXinSen** [comment]
@devgianlu Samsung S9 Android 9.0

**Comment by devgianlu** [comment]
I've added some tweaks for the next version that can help in some situations, but Android is very strict on who can access the external storage.

**Comment by devgianlu** [comment]
https://stackoverflow.com/questions/40068984/universal-way-to-write-to-external-sd-card-on-android

**Comment by devgianlu** [comment]
I thought we had a solution, but since `aria2c` is a separate process we would need the whole app to be granted the permission which isn't possible.

**Comment by liux-pro** [comment]
I found a way，it may help。
change download directory to `"sd Card root"+/Android/data/com.gianlu.aria2android/`
for my device it is:

> /storage/3E03-150D/Android/data/com.gianlu.aria2android

it works fine for me!

**Uninstalling Aria2Android app will delete this  directory  and the file you downloaded**

**Comment by UsernameIsAlreadyTakenByMe** [comment]
Hi,

I assume that ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION is missing:

https://developer.android.com/training/data-storage/manage-all-files
https://stackoverflow.com/questions/63842070/accessing-external-storage-in-android-api-29

The earlier stackoverflow link did not mention this:
https://stackoverflow.com/questions/40068984/universal-way-to-write-to-external-sd-card-on-android

**Comment by devgianlu** [comment]
@UsernameIsAlreadyTakenByMe the ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION permission has been added in Android 11 and won't solve the issue on most devices. That isn't a clean solution either as the app would be able to access all files and require additional trust from the user.
