### ISSUE TITLE
SSL/TLS handshake failure: unable to get local issuer certificate

### ISSUE THREAD

**Issue by nghialm269** [devgianlu/Aria2Android#20]
I get 

> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate

 when trying to download any file with https.
I'm using Aria2Android 2.0.2 (aria2 version 1.34.0) and latest Aria2App from F-Droid.

**Comment by devgianlu** [comment]
You need to update to 2.0.4, where this issue has been fixed. I don't think it is on F-Droid already, but you can download it from the releases page on GitHub.
