### ISSUE TITLE
[Feature Request] TV support ?

### ISSUE THREAD

**Issue by peerless2012** [devgianlu/Aria2Android#24]
Both TV UI support and TV Remote Controller support ?

**Comment by devgianlu** [comment]
I will eventually work on this. https://developer.android.com/training/tv/start/start

**Comment by devgianlu** [comment]
Closing in favor of #28.

**Comment by peerless2012** [comment]
any update？or need helper？I am an Android developer too.

**Comment by devgianlu** [comment]
A new release will be available soon.
