### ISSUE TITLE
un able to download to Micro SD card

### ISSUE THREAD

**Issue by liux-pro** [devgianlu/Aria2Android#32]
hi！

device:Sansung Glaxy Note3
latest version of this app

I can download things to the default directory,but when I change download directory to root of microSD card ，log says something is going wrong，no write permission。

App did ask me for file access permission，and I gave it to app。

![5E88B510FEEBC531A075DF3C40C9B91E](https://user-images.githubusercontent.com/20764978/74223906-ad35c400-4cf2-11ea-8fff-409684f3f724.jpg)

**Comment by devgianlu** [comment]
Please have a look at #19.
