### ISSUE TITLE
New Logo/Icon Design For Aria2Android

### ISSUE THREAD

**Issue by zularizal** [devgianlu/Aria2Android#7]
Hello @devgianlu , I'm a graphic designer, after I review your project, The current logo looks generic. I want to contribute by creating a unique and modern new logo for you. Don't worry, it's free. What do you think?

**Comment by devgianlu** [comment]
Effectively this logo has been made quite a while ago, by me, not a graphic designer. A new fresh logo wouldn't be bad!

**Comment by zularizal** [comment]
Okay. Give me time to make it. I will upload a new logo in my next reply.

**Comment by devgianlu** [comment]
I really like the second row, the center one especially. I might change this in the next version. Thank you!

How can I credit you in the app description?

**Comment by zularizal** [comment]
You can put my name or my github profile.

Okay, I'll make a pr for you.

**Comment by zularizal** [comment]
Hi @devgianlu , I have uploaded logo files to the drive

https://drive.google.com/open?id=1Or--4Yp3W0gfyapr9nhCwCZvsklLL40J

and also I have sent a pull request for you. #9

**Comment by devgianlu** [comment]
Hi @zularizal, I am renewing the design of this app by applying the latest Material Design standards and for this purpose I'd like to use some fancy icons. Can you help me with that? Thank you in advance.
