### ISSUE TITLE
Play Store version not working after update to 1.9.2

### ISSUE THREAD

**Issue by cacophobe** [devgianlu/Aria2Android#8]
After automatic update to version 1.9.2 it stopped working - black screen, no response to touch, frozen. Even clearing Data, Cache and reinstall didn't help. I downloaded the same version from GitHub Releases and it worked.

**Comment by devgianlu** [comment]
I know about this issue, I'm trying to fix it. It's due to the conflict
between Fabric and Firebase Crashlytics.

**Comment by devgianlu** [comment]
Apparently you can't have both Fierbase Crashlytics and Fabric Crashlytics. Fixed with v1.9.3.
