### ISSUE TITLE
Enable rpc-listen-all by default!

### ISSUE THREAD

**Issue by peerless2012** [devgianlu/Aria2Android#82]

**Comment by devgianlu** [comment]
Having this enabled exposes the RPC port outside of the device which could be a security threat if the user connects to unknown networks. For this reason I think it is better if the user consciously enables it.

**Comment by peerless2012** [comment]
As a control on settings together with rpc port and rpc token?

**Comment by devgianlu** [comment]
Will be available in the next release.

**Comment by peerless2012** [comment]
Sounds good!

**Comment by skygate2012** [comment]
This should be added by default or in the settings! Took me a while to realize that this parameter wasn't added.
@devgianlu Btw, is Aria2App is an all-in-one replacement for this app? I looked into it but didn't find any settings that could start a custom server open to the external network.
