### ISSUE TITLE
Can't set alternative download path

### ISSUE THREAD

**Issue by montvid** [devgianlu/Aria2Android#95]
Can't set alternative download path on Android 11 MIUI 12.5. I tried setting it via config command "dir" in the app but it does not work too. The download path resets to / no matter what I choose. Only solution is to reset the app and use the default path.

**Comment by devgianlu** [comment]
See https://github.com/devgianlu/Aria2App/wiki/Issues-with-SD-card

**Comment by montvid** [comment]
The default app path /Download works but /Download/anyfolder does not.
